CREATE TABLE EMPLOYEE (
    EMP_ID SERIAL PRIMARY KEY,
    EMP_NAME VARCHAR(100) NOT NULL,
    EMAIL_ID VARCHAR(100) UNIQUE NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL,
    CITY VARCHAR(50)
);

SELECT * FROM EMPLOYEE;



INSERT INTO EMPLOYEE (EMP_NAME, EMAIL_ID, DEPARTMENT, SALARY, CITY)
VALUES
('AMIT SHARMA', 'AMIT.SHARMA@TCS.COM', 'IT', 55000.00, 'BANGALORE'),
('PRIYA SINGH', 'PRIYA.SINGH@TCS.COM', 'HR', 48000.00, 'HYDERABAD'),
('RAHUL VERMA', 'RAHUL.VERMA@TCS.COM', 'FINANCE', 60000.00, 'PUNE'),
('NEHA DUBEY', 'NEHA.GUPTA@TCS.COM', 'TESTING', 52000.00, 'CHENNAI'),
('ROHIT KUMAR', 'ROHIT.KUMAR@TCS.COM', 'DEVELOPMENT', 70000.00, 'NOIDA');


-- UPDATE COMMAND 

UPDATE EMPLOYEE
SET SALARY = 85000.00
WHERE EMP_NAME = 'ROHIT KUMAR';


SELECT * FROM EMPLOYEE;


-- DELETE COMMAND


DELETE FROM EMPLOYEE
WHERE EMP_NAME = 'PRIYA SINGH';


-- ALTER COMMAND


ALTER TABLE EMPLOYEE
ADD COLUMN STATE VARCHAR(50);

-- ALTER DROP COMMAND

ALTER TABLE EMPLOYEE
DROP COLUMN STATE;

------------------------------------------------------------------

CREATE TABLE WORKER (
    WORKER_ID SERIAL PRIMARY KEY,
    WORKER_NAME VARCHAR(100) NOT NULL,
    EMAIL_ID VARCHAR(100) UNIQUE NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL,
    CITY VARCHAR(50),
    JOINING_DATE DATE
);

INSERT INTO WORKER (WORKER_NAME, EMAIL_ID, DEPARTMENT, SALARY, CITY, JOINING_DATE)
VALUES
('RAMESH KUMAR', 'RAMESH@COMPANY.COM', 'PRODUCTION', 30000.00, 'BHOPAL', '2024-01-15'),
('SURESH YADAV', 'SURESH@COMPANY.COM', 'MAINTENANCE', 32000.00, 'INDORE', '2023-11-20'),
('POOJA SHARMA', 'POOJA@COMPANY.COM', 'HR', 40000.00, 'PUNE', '2024-03-10'),
('ANKIT VERMA', 'ANKIT@COMPANY.COM', 'IT', 50000.00, 'NOIDA', '2023-09-05'),
('NEHA SINGH', 'NEHA@COMPANY.COM', 'FINANCE', 45000.00, 'HYDERABAD', '2024-02-01');


SELECT * FROM WORKER;

-- TRUNCATE 

TRUNCATE TABLE WORKER;


-- DROP 

DROP TABLE WORKER;