DROP TABLE IF EXISTS SALES_DATA;

CREATE TABLE IF NOT EXISTS SALES_DATA
(
	order_id		VARCHAR(20) PRIMARY KEY ,
	order_date		DATE,
	ship_date		DATE,
	ship_mode		VARCHAR(20),
	customer_id		VARCHAR(20),
	customer_name	VARCHAR(20)
	segment	
	country	
	city	
	state	
	postal_code	
	region	
	product_id	
	category	
	sub_category	
	product_name	
	sales_$	
	quantity	
	profit_$

);
SELECT * FROM SALES_DATA


-- date function 

SELECT CURRENT_DATE;
SELECT CURRENT_TIME;

SELECT CURRENT_TIMESTAMP;

-- date part function 

SELECT date_year ('year', TIMESTAMP '2021-04-03 22:04:07');
SELECT date_day ('Day', TIMESTAMP '2021-04-10 22:04:07');
SELECT date_mon('mon', TIMESTAMP '2021-08-03 22:04:07');	--mon = month
SELECT date_hour ('hour', TIMESTAMP '2021-04-03 22:04:07');	--hour= hour
SELECT date_min('min', TIMESTAMP '2021-04-03 22:04:07');	--min = minutes
SELECT date_sec('sec', TIMESTAMP '2021-04-03 22:04:07');  --sec= second

-- trunc function

SELECT date_trunc('hour', TIMESTAMP '2021-04-03 22:04:07') -- trunc ko specific compelete displaay karega  

SELECT date_trunc('year', TIMESTAMP '2021-04-03 22:04:07')

-- justify

SELECT justify_days(interval '65 DAYS'); --This converts days into months properly 

SELECT Justify_hours(interval '30 hours');


-- Get total Sales month wise
SELECT ORDER_DATE , SUM(SALES_$)
FROM SALES_DATA
GROUP BY ORDER_DATE;

-- EXTRACT MONTH NUMBER FROM DATE 

SELECT EXTRACT (MONTH FROM ORDER_DATE)
FROM SALES_DATA;

-- MONTH NAME EXTRACT 

SELECT TO_CHAR(ORDER_DATE, 'month')
FROM SALES_DATA;

-- MONTH WISE TOTAL SALES 

SELECT TO_CHAR(ORDER_DATE, 'month') , SUM(SALES_$)
FROM SALES_DATA
GROUP BY TO_CHAR(ORDER_DATE, 'month');

-- DAY WISE TOTAL SALES 

SELECT TO_CHAR(ORDER_DATE, 'DAY') , SUM(SALES_$)
FROM SALES_DATA
GROUP BY TO_CHAR(ORDER_DATE, 'DAY');

-- YEAR WISE TOTAL SALES 


SELECT TO_CHAR(ORDER_DATE, 'year') , SUM(SALES_$)
FROM SALES_DATA
GROUP BY TO_CHAR(ORDER_DATE, 'year');


-- 4. AGE FUNCTION IN SQL

SELECT AGE ('2004-03-24','2026-04-09' );
SELECT AGE (CURRENT_DATE, '2004-03-24' );


SELECT AGE (ship_date, order_date) AS DAYS_BETWEEN 
FROM SALES_DATA;

SELECT ship_date, order_date, AGE (ship_date, order_date) AS DAYS_BETWEEN 
FROM SALES_DATA;

SELECT ship_date, AGE (CURRENT_DATE, order_date) AS DAYS_BETWEEN 
FROM SALES_DATA;

-- STRING FUNCTION

-- 1.UPPER FUNCTION

SELECT CUSTOMER_NAME ,UPPER(CUSTOMER_NAME)
FROM SALES_DATA;


-- 2.LOWER FUNCTION

SELECT CUSTOMER_NAME ,LOWER(CUSTOMER_NAME)
FROM SALES_DATA;


-- 3.LENGTH FUNCTION

SELECT CUSTOMER_NAME ,LENGTH(CUSTOMER_NAME)
FROM SALES_DATA;


-- 4. CONCAT FUNCTION

SELECT CUSTOMER_NAME, SEGMENT ,CONCAT(CUSTOMER_NAME, SEGMENT)
FROM SALES_DATA;

SELECT CUSTOMER_NAME, SEGMENT ,CONCAT(CUSTOMER_NAME,'-', SEGMENT)
FROM SALES_DATA;


-- 5. REPLACE FUNCTION

SELECT REGION, REPLACE(REGION, 'Central', 'North') AS NewZone
FROM SALES_DATA;

-- 6. SUBSTRING FUNCTION

SELECT CUSTOMER_NAME,SUBSTRING(CUSTOMER_NAME, 1,5)
FROM SALES_DATA;


-- 6. STRINGPOSTION OR STRPOS FUNCTION

SELECT CUSTOMER_NAME,STRPOS(CUSTOMER_NAME,' ')
FROM SALES_DATA;
 

-- GET SEPRATE FIRST NAME FORM CUSTOMER NAME 


SELECT CUSTOMER_NAME, SUBSTRING(CUSTOMER_NAME, 1, STRPOS(CUSTOMER_NAME,' '))
FROM SALES_DATA;


-- GET SEPRATE LAST NAME FORM CUSTOMER NAME 


SELECT CUSTOMER_NAME, SUBSTRING(CUSTOMER_NAME, STRPOS(CUSTOMER_NAME,' '), LENGTH(CUSTOMER_NAME)-STRPOS(CUSTOMER_NAME,' '))
FROM SALES_DATA;